### ISSUE TITLE
Implement Linear Search

### ISSUE THREAD

**Issue by shubham2704** [rohan8594/DS-Algos#11]
# Implementation of Linear Search algorithm 

Already completed in :
 #6  - Python

you can work on :
C++
java
javascript
ruby
go
php
c#

**Comment by smallblack9** [comment]
Hi, may I work on this? 
If yes, should I add all the files with different language to the '/algorithms/Searching/' folder (same as LinearSearch.py)? I can do C++, Java, Ruby, C#, would you like all the file with the same name 'LinearSearch' (Pascal)? Should I take a user input or just use the same data as in LinearSearch.py?

**Comment by rohan8594** [comment]
@smallblack9 please pick another algorithm/question. This one has already been submitted
