### ISSUE TITLE
LeetCode problem #1551- Minimum Operations to Make Array Equal

### ISSUE THREAD

**Issue by saurabh-172** [rohan8594/DS-Algos#38]
**Problem**-
You have an array arr of length n where arr[i] = (2 * i) + 1 for all valid values of i (i.e. 0 <= i < n).
In one operation, you can select two indices x and y where 0 <= x, y < n and subtract 1 from arr[x] and add 1 to arr[y] (i.e. perform arr[x] -=1 and arr[y] += 1). The goal is to make all the elements of the array equal. It is guaranteed that all the elements of the array can be made equal using some operations.
Given an integer n, the length of the array. Return the minimum number of operations needed to make all the elements of arr equal.
**problem difficulty**: medium

**problem link**: https://leetcode.com/problems/minimum-operations-to-make-array-equal/
**language used**: python

I'm new to open source contribution and hactoberfest and I would like to contribute to arrays and strings repo by adding a solution to this problem. I checked and this was not been added and I read the contribution guide also, please assign me if not assigned anyone on this.

**Comment by rohan8594** [comment]
@saurabh-172 assigned

**Comment by saurabh-172** [comment]
I have made a PR please check it, it should close #38

**Comment by saurabh-172** [comment]
Please reply I'm getting worried thinking of that **why are you not replying to my PR did I do something wrong**.

**Comment by rohan8594** [comment]
@saurabh-172 nothing wrong with the pr. I work on weekdays so will only have time to review and merge over the weekend.
