### ISSUE TITLE
LeetCode #36 - Valid Sudoku 

### ISSUE THREAD

**Issue by Swarn10** [rohan8594/DS-Algos#7]
**Problem Statement** - Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the following rules: 
- Each row must contain the digits 1-9 without repetition.
- Each column must contain the digits 1-9 without repetition.
- Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.  

**Problem Link** - LeetCode problem number 36 (https://leetcode.com/problems/valid-sudoku/)

**Programming Language to be used** - Python3

**Comment by Swarn10** [comment]
@rohan8594 I would like to solve and contribute this problem to the repo. This problem is currently missing from the repo. Please assign this issue to me. Will be happy to help.

**Comment by rohan8594** [comment]
@Swarn10 This looks good. Pls go through the readme and contribution guides before creating your pr. They've been updated.

**Comment by Swarn10** [comment]
@rohan8594 The question that I am contributing is a leetcode medium question but belongs to the **Hash Table** bucket. In the repo there is no directory for Hash table related problems in the Leetcode folder. What should I do ?

**Comment by rohan8594** [comment]
@Swarn10 I think this question can just sit inside `leetcode -> medium`.

**Comment by meghanagottapu** [comment]
can I work on this issue?

**Comment by Swarn10** [comment]
@rohan8594 I have added my Python solution to the Leetcode problem Valid Sudoku that is referred to in this issue and made a PR. Please check.

**Comment by rohan8594** [comment]
Thanks for the contribution @Swarn10
